
- link:
    ~/.bash_profile: shells/bash/linux.bash_profile
    ~/.bashrc: shells/bash/linux.bashrc
    ~/.bash_logout: shells/bash/linux.bash_logout
    ~/.config/git/git-completion.bash: shells/bash/git-completion.bash
