# Setup dotfiles for bash shell on Windows
- link:
    ~/.bash_profile: shells/bash/.bash_profile
    ~/.bashrc: shells/bash/.bashrc
    ~/.bashrc_local_after: shells/bash/local/after.windows.bashrc
    ~/.config/git/git-completion.bash: shells/bash/git-completion.bash
