# Setup dotfiles for git configuration
- link:
    ~/.config/git/config: development/git/gitconfig
    ~/.config/git/aliases: development/git/gitconfig.aliases
    ~/.config/git/ignore: development/git/gitignore_global
