
- link:
    ~/.pythonrc: development/python/pythonrc.py
    ~/.pylintrc: development/python/pylintrc.ini
    ~/.flake8: development/python/flake8.ini
    ~/.config/mypy/config: development/python/mypy.ini

- shell:
    - [conda update -y conda, Updating conda]
    - [conda install -y pip cython flake8 pylint mypy ipython jupyter, Installing conda python packages]
    - [pip install --user -U -r ./development/python/req.windows.txt, Installing pip python packages]
