
- link:
    ~/.pythonrc: development/python/pythonrc.py
    ~/.ipython/profile_default/ipython_config.py: development/python/ipython_config.linux.py
    ~/.pylintrc: development/python/pylintrc.ini
    ~/.config/flake8: development/python/flake8.ini
    ~/.config/mypy/config: development/python/mypy.ini

- shell:
    - [~/anaconda3/bin/conda update -y conda, Updating conda]
    - [~/anaconda3/bin/conda install -y pip cython flake8 pylint mypy ipython jupyter, Installing conda python packages]
    - [~/anaconda3/bin/pip install --user -U -r ./development/python/req.linux.txt, Installing pip python packages]
