# Setup configs for Python, IPython, Conda, and linting on Windows
- link:
    ~/.config/python/pythonrc.py: development/python/pythonrc.py
    ~/.config/ipython/profile_default/ipython_config.py: development/python/ipython_config.linux.py
    ~/.config/pylintrc: development/python/pylintrc.ini
    ~/.flake8: development/python/flake8.ini
    ~/.config/conda/condarc: development/python/condarc.yaml
    ~/.config/yapf/style: development/python/yapf.ini

# Create python cache directory
- create:
    - ~/.cache/python
