
- link:
    ~/.pythonrc: development/python/pythonrc.py
    ~/.ipython/profile_default/ipython_config.py: development/python/ipython_config.linux.py
    ~/.pylintrc: development/python/pylintrc.ini
    ~/.config/flake8: development/python/flake8.ini
    ~/.config/mypy/config: development/python/mypy.ini

