# Setup configs for Python, IPython, Conda, and linting on Linux
- link:
    ~/.config/python/pythonrc.py: development/python/pythonrc.py
    ~/.config/ipython/profile_default/ipython_config.py: development/python/ipython_config.linux.py
    ~/.config/pylintrc: development/python/pylintrc.ini
    ~/.config/flake8: development/python/flake8.ini
    ~/.config/conda/condarc: development/python/condarc.yaml

# Run a command to create an empty python history file
- shell:
    - [mkdir -p ~/.cache/python]
    - [touch ~/.cache/python/history]
