# Setup common sh dotfiles
# inputrc: Common settings for all programs editing/reading command line
- link:
    ~/.config/sh: shells/sh/.config/sh
    ~/.profile: shells/sh/linux.profile
    ~/.config/readline/inputrc: shells/.inputrc
