# Setup common sh dotfiles
# inputrc: Common settings for all programs editing/reading command line
- link:
    ~/.config/sh: shells/sh/.config/sh
    ~/.profile: shells/bash/linux.profile
    ~/.inputrc: shells/.inputrc
