
- shell:
    - [./terminal/fonts/install.sh DejaVuSansMono, Installing powerline fonts - DejaVuSansMono]
    - [git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell, cloning terminal colors]
