
- link:
    '%APPDATA%/wsltty/themes': terminal/mintty/themes
    '%APPDATA%/wsltty/config': terminal/mintty/config
    '%USERPROFILE%/cmder/config/user_aliases.cmd': terminal/cmder/user_aliases.cmd
    '%USERPROFILE%/cmder/config/user_profile.cmd': terminal/cmder/user_profile.cmd
    '%USERPROFILE%/cmder/config/user_profile.sh': terminal/cmder/user_profile.sh
    '%USERPROFILE%/tux.ico': terminal/windows/tux.ico

- shell:
    - [powershell -ExecutionPolicy Bypass "& ./terminal/fonts/install.ps1 DejaVuSansMono", Installing powerline fonts - DejaVuSansMono]
    - [powershell -ExecutionPolicy Bypass "./terminal/colors/conemu-themes/Install-ConEmuTheme.ps1 -ConfigPath '%ConEmuDir%/ConEmu.xml' -Operation Add -ThemePathOrName './terminal/colors/conemu-themes/themes/dracula.xml'", Installing Dracula Cmder Theme]
    - [powershell -ExecutionPolicy Bypass "./terminal/colors/conemu-themes/Install-ConEmuTheme.ps1 -ConfigPath '%ConEmuDir%/ConEmu.xml' -Operation Add -ThemePathOrName './terminal/colors/conemu-themes/themes/spacemacs-dark.xml'", Installing Spacemacs Cmder Theme]
