
- link:
    ~/.config/mintty/config/themes: terminal

- shell:
    - [powershell -ExecutionPolicy Bypass "& ./terminal/fonts/install.ps1 DejaVuSansMono", Installing powerline fonts - DejaVuSansMono]
    - [powershell -ExecutionPolicy Bypass "./terminal/colors/conemu-themes/Install-ConEmuTheme.ps1 -ConfigPath '%ConEmuDir%/ConEmu.xml' -Operation Add -ThemePathOrName './terminal/colors/conemu-themes/themes/dracula.xml'", Installing Dracula Cmder Theme]
    - [powershell -ExecutionPolicy Bypass "./terminal/colors/conemu-themes/Install-ConEmuTheme.ps1 -ConfigPath '%ConEmuDir%/ConEmu.xml' -Operation Add -ThemePathOrName './terminal/colors/conemu-themes/themes/spacemacs-dark.xml'", Installing Spacemacs Cmder Theme]
