
- shell:
    - [powershell "& ./terminal/fonts/install.ps1 DejaVuSansMono", Installing powerline fonts - DejaVuSansMono]
    - [powershell "./terminal/colors/base16-conemu/Install-ConEmuTheme.ps1 -ConfigPath ../../../cmder/vendor/conemu-maximus5/ConEmu.xml -Operation Add -ThemePathOrName ./terminal/colors/base16-conemu/themes/base16-ocean.xml", Installing Cmder Theme]
