# Install tools for Linux that aren't done through `apt` or `pip`
- shell:
    - eval $([[ ! -d ~/.fzf ]] && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf)
    - [~/.fzf/install --all --xdg --no-update-rc, Installing fzf]
