# Setup dotfiles for ZSH shell
- link:
    ~/.config/zsh: shells/zsh/
    ~/.zshrc: shells/zsh/.zshrc
    ~/.zprofile: shells/zsh/.zprofile
    ~/.zshenv: shells/zsh/.zshenv
# Make ZSH cache directory
- shell:
    - [mkdir -p ~/.cache/zsh]
