# Dylan Thomas's custom .condarc file
# This file is setup to be located at ~/.config/conda/condarc

# channel locations. These override conda defaults, i.e., conda will
# search *only* the channels listed here, in the order given.
# Use "defaults" to automatically include all default channels.
# Non-url channels will be interpreted as Anaconda.org usernames
# (this can be changed by modifying the channel_alias key; see below).
# The default is just 'defaults'.
channels:
  - conda-forge
  - defaults

# Show channel URLs when displaying what is going to be downloaded
# and in 'conda list'. The default is False.
show_channel_urls: True

# Define where conda should store environments
env_dirs:
  - ~/.config/conda/envs

# Define where conda should store packages
pkg_dirs:
  - ~/.config/conda/pkgs
